# overriding conda-forge-pinnings defined in
# https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/master/recipe/conda_build_config.yaml

# clangxx isn't standalone on linux, it depends on gcc
# Isuru from conda-forge reccomended explicitly adding clangxx
# but we could also add a clang_linux-64 metapackage so that
# clang could be listed in the compiler matrix
# https://gitter.im/conda-forge/conda-forge.github.io?at=5e5feaf7ec7f8746aab200c4
# is Isuru's reply to my question in:
# https://gitter.im/conda-forge/conda-forge.github.io?at=5e5f4ae2376d882250cd5d5c
# # conda-forge uses gcc on linux and clang on osx
# # we're only supporting clang on both platforms
# c_compiler:
#     - clang
# c_compiler_version:
#     - 9
# cxx_compiler:
#     - clangxx
# cxx_compiler_version:
#     - 9

# override macos APK min version.
# conda-forge supports from 10.9 but we
# have code that needs 10.13.
# See https://sifive.atlassian.net/wiki/x/0IBBJw
# for details
macos_min_version:             # [osx]
  - 10.13                      # [osx]
MACOSX_DEPLOYMENT_TARGET:      # [osx]
  - 10.13                      # [osx]

zip_keys:                       # [osx]
  -                             # [osx]
    - macos_min_version         # [osx]
    - MACOSX_DEPLOYMENT_TARGET  # [osx]


c_compiler:
  - gcc                        # [linux]
  - clang                      # [osx]
c_compiler_version:            # [unix]
  - 14                         # [osx]
  - 11                         # [osx]
  - 11                         # [linux]
  - 10                         # [linux]
cxx_compiler:
  - gxx                        # [linux]
  - clangxx                    # [osx]
cxx_compiler_version:          # [unix]
  - 14                         # [osx]
  - 11                         # [osx]
  - 11                         # [linux]
  - 10                         # [linux]
linux_clang_version:           # [linux]
  - 14                         # [linux]
  - 11                         # [linux]
docker_image:
  - quay.io/condaforge/linux-anvil-cos7
  - quay.io/condaforge/linux-anvil-cos7
cdt_name:
  - cos6
  - cos6

# conda-forge-pinnings-feedstock/recipe/conda_build_config.yaml
# uses c_compiler_version and cxx_compiler_version in a zip_keys
# https://docs.conda.io/projects/conda-build/en/latest/resources/variants.html#coupling-keys
# They typically only have a single version of the compilers that they
# are building packages with at a time.  However, we want to regress
# across a few.  That means we need to balance the size of the
# elements of the zip_keys.  I'm going to override those here
# as well so that it is easier to see what we're doing.
# I dropped the cuda stuff out of conda-forge zip_keys because
# we don't care about CUDA as we aren't using it.
zip_keys:
    -
        - c_compiler_version
        - cxx_compiler_version
        - linux_clang_version  # [linux]
        - cdt_name      # [linux]
        - docker_image  # [linux]
    -
        - python
        - numpy
        - python_impl
